version: '3.7'

services:

  nginx-server:
    build:
      context: ./docker/nginx
    image: $NGINX_SERVER_CONTAINER_NAME:$APP_VERSION
    container_name: $NGINX_SERVER_CONTAINER_NAME
    restart: always
    depends_on:
      - php-fpm
    networks:
      - internal-net
    ports:
      - '$NGINX_SERVER_PORT:8080'
    volumes:
      - source-volume:/var/www/html/default:cached
      - php-run-volume:/var/run/php:delegated
      - $PWD/docker/nginx/config/conf.d:/etc/nginx/conf.d:cached
      - $PWD/var/log/nginx:/var/log/nginx:delegated

  php-fpm:
    build:
      context: ./docker/php
    image: $PHP_FPM_CONTAINER_NAME:$APP_VERSION
    container_name: $PHP_FPM_CONTAINER_NAME
    restart: always
    depends_on:
      - mysql-database
    networks:
      - database-net
      - internal-net
    volumes:
      - source-volume:/var/www/html/default:cached
      - php-run-volume:/var/run/php:delegated
      - $PWD/docker/php/config/php-fpm.d:/usr/local/etc/php-fpm.d:cached
      - $PWD/var/log/php:/var/log/php:delegated

  mysql-database:
    build:
      context: ./docker/mysql
    image: $MYSQL_DATABASE_CONTAINER_NAME:$APP_VERSION
    container_name: $MYSQL_DATABASE_CONTAINER_NAME
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_DATABASE_ROOT_PASSWORD
      - MYSQL_LOG_CONSOLE=
    networks:
      - database-net
    expose:
      - '3306'
    volumes:
      - mysql-data-volume:/var/lib/mysql:cached
      - $PWD/docker/mysql/config/my.cnf.d:/etc/my.cnf.d:cached
      - $PWD/var/log/mysql:/var/log/mysql:delegated

volumes:

  source-volume:
    driver: local
    name: source-volume
    driver_opts:
      type: none
      o: bind,X-mount.mkdir
      device: $PWD

  php-run-volume:
    driver: local
    name: php-run-volume
    driver_opts:
      type: none
      o: bind,X-mount.mkdir
      device: $PWD/var/run/php

  mysql-data-volume:
    driver: local
    name: mysql-data-volume
    driver_opts:
      type: none
      o: bind,X-mount.mkdir
      device: $PWD/var/data/mysql

networks:

  database-net:
    driver: bridge
    name: database-net

  internal-net:
    driver: bridge
    name: internal-net
